apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    role: client
  namespace: helm-elk
spec:
  rules:
    - host: elkprodurl.nic.in
      http:
        paths:
          - backend:
              serviceName: http-rest
              servicePort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: http-rest
  namespace: helm-elk
  labels:
    app: elasticsearch
    role: client
spec:
 # type: LoadBalancer
  type: ClusterIP
  selector:
    app: elasticsearch
    role: client
  ports:
    - port: 9200
      name: http-rest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-client
  namespace: helm-elk
  labels:
    app: elasticsearch
    role: client
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: client
  template:
    metadata:
      labels:
        app: elasticsearch
        role: client
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        #image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
        image: chub.cloud.gov.in/library/elasticsearch:7.16.2
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 2
            requests:
              cpu: 1
        ports:
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        - containerPort: 9200
          name: rest
          protocol: TCP
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: node.name
            value: $(HOSTNAME).es.helm-elk.svc.cluster.local
          - name: network.host
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: cluster.name
            value: es-cluster-1
          - name: cluster.initial_master_nodes
            value: "es-master-0.es.helm-elk.svc.cluster.local"
          - name: discovery.seed_hosts
            value: "es-master-0.es.default.helm-elk.cluster.local,es-master-1.es.helm-elk.svc.cluster.local,es-master-2.es.helm-elk.svc.cluster.local"
          - name: node.master
            value: "false"
          - name: node.data
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms4G -Xmx4G" 
