apiVersion: v1
kind: ConfigMap
metadata:
  namespace: helm-elk 
  name: es-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0
    node:
      master: true
      data: true
      ingest: true
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
