apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk
  namespace: helm-elk
spec:
  storageClassName: cephblock
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
