kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: helm-elk
  labels:
    app: kibana
spec:
  selector:
    app: kibana
    #clusterIP: None
  type: ClusterIP
  ports:
    - port: 5601
      name: kibana-gui

